version: '2'

services:
 gitlab:
  image: gitlab/gitlab-ce
  restart: always
  environment:
    GITLAB_OMNIBUS_CONFIG: |
  ports:
    - "80:80"
    - "443:443"
    - "2222:22"
  volumes:
    - /opt/gitlab/config:/etc/gitlab
    - /opt/gitlab/logs:/var/log/gitlab
    - /opt/gitlab/data:/var/opt/gitlab
